### ISSUE TITLE
图片放大后可以上下划出屏幕

### ISSUE THREAD

**Issue by ghostlordstar** [g763007297/GQImageVideoViewer#1]
图片放大后，可以上下划，并且可以将图片内容划到屏幕外，这个有接口控制么？

**Comment by g763007297** [comment]
这个功能在我另外的一个库里面是实现了的，你可以参考一下 https://github.com/g763007297/ImageViewer#自定义图片显示页面

**Comment by ghostlordstar** [comment]
OK，吃过饭看一下

发自我的 iPhone

在 2017年7月31日，下午12:07，g763007297 <notifications@github.com<mailto:notifications@github.com>> 写道：


这个功能在我另外的一个库里面是实现了的，你可以参考一下 https://github.com/g763007297/ImageViewer#自定义图片显示页面<https://github.com/g763007297/ImageViewer#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA%E9%A1%B5%E9%9D%A2>
