### ISSUE TITLE
直接退出控制器不能走disMiss方法，导致下次赋值时崩溃

### ISSUE THREAD

**Issue by ghostlordstar** [g763007297/GQImageVideoViewer#2]
##  直接退出控制器不能走disMiss方法，导致下次赋值时崩溃
![dissmiss](https://user-images.githubusercontent.com/12198944/28773631-f521cc50-761c-11e7-97db-da3bc7ab48ef.gif)
在浏览界面直接退出控制器，不能触发dissMiss方法，导致数组不能被清空，再次给自定义图片或视频展示模板类名赋值时就会抛出异常

## 解决方案
>* 1.在控制器的viewDidDisappear方法中手动调用dissMiss方法

>* 2.在封装的内部监测showView的状态，当showView为空时自动调用dissMiss

**Comment by g763007297** [comment]
这个是谁展示谁就要负责dissMiss。

**Comment by ghostlordstar** [comment]
好的，明白了

发自我的 iPhone

在 2017年8月1日，下午2:40，g763007297 <notifications@github.com<mailto:notifications@github.com>> 写道：


这个是谁展示谁就要负责dissMiss。
