### ISSUE TITLE
老哥，为什么不加个结束浏览的回调？

### ISSUE THREAD

**Issue by ghostlordstar** [g763007297/GQImageVideoViewer#3]
没有结束浏览的回调

**Comment by g763007297** [comment]
非常抱歉，这个工程已经落下了几个版本的代码同步了，很多功能都是在https://github.com/g763007297/ImageViewer  这个里面，因为没有时间同步，所以一直就放在这里了。

**Comment by ghostlordstar** [comment]
OK，懂了
